// src/redux/types.js

// API Middleware specific
export const API_REQUEST = 'API_REQUEST';

// Class Timetable
export const FETCH_CLASSES_REQUEST = 'FETCH_CLASSES_REQUEST';
export const FETCH_CLASSES_SUCCESS = 'FETCH_CLASSES_SUCCESS';
export const FETCH_CLASSES_FAILURE = 'FETCH_CLASSES_FAILURE';

// Students (overall list)
export const FETCH_STUDENTS_REQUEST = 'FETCH_STUDENTS_REQUEST';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAILURE = 'FETCH_STUDENTS_FAILURE';

// Single Student Data
export const FETCH_SINGLE_STUDENT_REQUEST = 'FETCH_SINGLE_STUDENT_REQUEST';
export const FETCH_SINGLE_STUDENT_SUCCESS = 'FETCH_SINGLE_STUDENT_SUCCESS';
export const FETCH_SINGLE_STUDENT_FAILURE = 'FETCH_SINGLE_STUDENT_FAILURE';

// --- NEW: Add Student ---
export const ADD_STUDENT_REQUEST = 'ADD_STUDENT_REQUEST';
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS';
export const ADD_STUDENT_FAILURE = 'ADD_STUDENT_FAILURE';

// --- NEW: Add Weekly Marks for Student ---
export const ADD_WEEKLY_MARKS_REQUEST = 'ADD_WEEKLY_MARKS_REQUEST';
export const ADD_WEEKLY_MARKS_SUCCESS = 'ADD_WEEKLY_MARKS_SUCCESS';
export const ADD_WEEKLY_MARKS_FAILURE = 'ADD_WEEKLY_MARKS_FAILURE';

// Employees
export const FETCH_EMPLOYEES_REQUEST = 'FETCH_EMPLOYEES_REQUEST';
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS';
export const FETCH_EMPLOYEES_FAILURE = 'FETCH_EMPLOYEES_FAILURE';

// --- NEW: Add Employee ---
export const ADD_EMPLOYEE_REQUEST = 'ADD_EMPLOYEE_REQUEST';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_FAILURE = 'ADD_EMPLOYEE_FAILURE';


// Chart Data
export const UPDATE_DASHBOARD_CHART_DATA = 'UPDATE_DASHBOARD_CHART_DATA';

// Authentication/Global Error
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR';
export const LOGOUT = 'LOGOUT';

// src/redux/types.js

// ... existing types ...

// --- NEW: Add Timetable Entry ---
export const ADD_TIMETABLE_REQUEST = 'ADD_TIMETABLE_REQUEST';
export const ADD_TIMETABLE_SUCCESS = 'ADD_TIMETABLE_SUCCESS';
export const ADD_TIMETABLE_FAILURE = 'ADD_TIMETABLE_FAILURE';

// ... other existing types ...
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SET_USER_DATA = 'SET_USER_DATA';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

// Student Payment Status Update
export const UPDATE_STUDENT_PAYMENT_REQUEST = 'UPDATE_STUDENT_PAYMENT_REQUEST';
export const UPDATE_STUDENT_PAYMENT_SUCCESS = 'UPDATE_STUDENT_PAYMENT_SUCCESS';
export const UPDATE_STUDENT_PAYMENT_FAILURE = 'UPDATE_STUDENT_PAYMENT_FAILURE';

export const FETCH_WEEKLY_MARKS_REQUEST = 'FETCH_WEEKLY_MARKS_REQUEST';
export const FETCH_WEEKLY_MARKS_SUCCESS = 'FETCH_WEEKLY_MARKS_SUCCESS';
export const FETCH_WEEKLY_MARKS_FAILURE = 'FETCH_WEEKLY_MARKS_FAILURE';

export const UPDATE_STUDENT_PAYMENT_STATUS_REQUEST = 'UPDATE_STUDENT_PAYMENT_STATUS_REQUEST';
export const UPDATE_STUDENT_PAYMENT_STATUS_SUCCESS = 'UPDATE_STUDENT_PAYMENT_STATUS_SUCCESS';
export const UPDATE_STUDENT_PAYMENT_STATUS_FAILURE = 'UPDATE_STUDENT_PAYMENT_STATUS_FAILURE';

export const UPDATE_STUDENT_CLASSES_REQUEST = 'UPDATE_STUDENT_CLASSES_REQUEST';
export const UPDATE_STUDENT_CLASSES_SUCCESS = 'UPDATE_STUDENT_CLASSES_SUCCESS';
export const UPDATE_STUDENT_CLASSES_FAILURE = 'UPDATE_STUDENT_CLASSES_FAILURE';

export const DELETE_TIMETABLE_REQUEST = 'DELETE_TIMETABLE_REQUEST'
export const DELETE_TIMETABLE_SUCCESS = 'DELETE_TIMETABLE_SUCCESS'
export const DELETE_TIMETABLE_FAILURE = 'DELETE_TIMETABLE_FAILURE'

export const UPDATE_TIMETABLE_REQUEST = 'UPDATE_TIMETABLE_REQUEST'
export const UPDATE_TIMETABLE_SUCCESS = 'UPDATE_TIMETABLE_SUCCESS'
export const UPDATE_TIMETABLE_FAILURE = 'UPDATE_TIMETABLE_FAILURE'

export const FETCH_PAYMENTS_REQUEST = 'FETCH_PAYMENTS_REQUEST'
export const FETCH_PAYMENTS_SUCCESS = 'FETCH_PAYMENTS_SUCCESS'
export const FETCH_PAYMENTS_FAILURE = 'FETCH_PAYMENTS_FAILURE'

export const FETCH_TOTAL_PAYMENTS_SUCCESS = 'FETCH_TOTAL_PAYMENTS_SUCCESS'


export const ADD_STUDENT_CLEAR_STATUS = 'ADD_STUDENT_CLEAR_STATUS'

export const ADD_DEMO_CLASS_REQUEST = 'ADD_DEMO_CLASS_REQUEST';
export const ADD_DEMO_CLASS_SUCCESS = 'ADD_DEMO_CLASS_SUCCESS';
export const ADD_DEMO_CLASS_FAILURE = 'ADD_DEMO_CLASS_FAILURE';
export const FETCH_DEMO_CLASSES_REQUEST = 'FETCH_DEMO_CLASSES_REQUEST';
export const FETCH_DEMO_CLASSES_SUCCESS = 'FETCH_DEMO_CLASSES_SUCCESS';
export const FETCH_DEMO_CLASSES_FAILURE = 'FETCH_DEMO_CLASSES_FAILURE';


// NEW: Action Types for updating status
export const UPDATE_DEMO_CLASS_STATUS_REQUEST = 'UPDATE_DEMO_CLASS_STATUS_REQUEST';
export const UPDATE_DEMO_CLASS_STATUS_SUCCESS = 'UPDATE_DEMO_CLASS_STATUS_SUCCESS';
export const UPDATE_DEMO_CLASS_STATUS_FAILURE = 'UPDATE_DEMO_CLASS_STATUS_FAILURE';
export const GENERATE_AND_SAVE_TIMETABLES_REQUEST = 'GENERATE_AND_SAVE_TIMETABLES_REQUEST';
export const GENERATE_AND_SAVE_TIMETABLES_SUCCESS = 'GENERATE_AND_SAVE_TIMETABLES_SUCCESS';
export const GENERATE_AND_SAVE_TIMETABLES_FAIL = 'GENERATE_AND_SAVE_TIMETABLES_FAIL';

  // Add new action types (e.g., in ../redux/actionTypes.js)
export const FETCH_AUTOTIMETABLES_REQUEST = 'FETCH_AUTOTIMETABLES_REQUEST';
export const FETCH_AUTOTIMETABLES_SUCCESS = 'FETCH_AUTOTIMETABLES_SUCCESS';
export const FETCH_AUTOTIMETABLES_FAILURE = 'FETCH_AUTOTIMETABLES_FAILURE';

export const SAVE_AUTOTIMETABLES_REQUEST = 'SAVE_AUTOTIMETABLES_REQUEST';
export const SAVE_AUTOTIMETABLES_SUCCESS = 'SAVE_AUTOTIMETABLES_SUCCESS';
export const SAVE_AUTOTIMETABLES_FAILURE = 'SAVE_AUTOTIMETABLES_FAILURE';

export const UPDATE_AUTOTIMETABLE_REQUEST = 'UPDATE_AUTOTIMETABLE_REQUEST';
export const UPDATE_AUTOTIMETABLE_SUCCESS = 'UPDATE_AUTOTIMETABLE_SUCCESS';
export const UPDATE_AUTOTIMETABLE_FAILURE = 'UPDATE_AUTOTIMETABLE_FAILURE';

export const DELETE_AUTOTIMETABLE_REQUEST = 'DELETE_AUTOTIMETABLE_REQUEST';
export const DELETE_AUTOTIMETABLE_SUCCESS = 'DELETE_AUTOTIMETABLE_SUCCESS';
export const DELETE_AUTOTIMETABLE_FAILURE = 'DELETE_AUTOTIMETABLE_FAILURE';

export const SAVE_AUTOGENERATED_TIMETABLES_REQUEST = 'SAVE_AUTOGENERATED_TIMETABLES_REQUEST';
export const SAVE_AUTOGENERATED_TIMETABLES_SUCCESS = 'SAVE_AUTOGENERATED_TIMETABLES_SUCCESS';
export const SAVE_AUTOGENERATED_TIMETABLES_FAILURE = 'SAVE_AUTOGENERATED_TIMETABLES_FAILURE';

export const UPDATE_AUTO_TIMETABLE_TOPIC_REQUEST = 'UPDATE_AUTO_TIMETABLE_TOPIC_REQUEST';
export const UPDATE_AUTO_TIMETABLE_TOPIC_SUCCESS = 'UPDATE_AUTO_TIMETABLE_TOPIC_SUCCESS';
export const UPDATE_AUTO_TIMETABLE_TOPIC_FAILURE = 'UPDATE_AUTO_TIMETABLE_TOPIC_FAILURE';

export const UPDATE_STUDENT_FIELD_REQUEST = 'UPDATE_STUDENT_FIELD_REQUEST';
export const UPDATE_STUDENT_FIELD_SUCCESS = 'UPDATE_STUDENT_FIELD_SUCCESS';
export const UPDATE_STUDENT_FIELD_FAILURE = 'UPDATE_STUDENT_FIELD_FAILURE';

// Example: src/redux/actionTypes.js
export const UPDATE_STUDENT_REQUEST = 'UPDATE_STUDENT_REQUEST';
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS';
export const UPDATE_STUDENT_FAILURE = 'UPDATE_STUDENT_FAILURE';

export const DELETE_STUDENT_REQUEST = 'DELETE_STUDENT_REQUEST';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const DELETE_STUDENT_FAILURE = 'DELETE_STUDENT_FAILURE';

export const DELETE_DEMO_CLASS_REQUEST = "DELETE_DEMO_CLASS_REQUEST";
export const DELETE_DEMO_CLASS_SUCCESS = "DELETE_DEMO_CLASS_SUCCESS";
export const DELETE_DEMO_CLASS_FAILURE = "DELETE_DEMO_CLASS_FAILURE";

export const UPDATE_DEMO_CLASS_REQUEST = "UPDATE_DEMO_CLASS_REQUEST";
export const UPDATE_DEMO_CLASS_SUCCESS = "UPDATE_DEMO_CLASS_SUCCESS";
export const UPDATE_DEMO_CLASS_FAILURE = "UPDATE_DEMO_CLASS_FAILURE";

export const FETCH_EXPENDITURES_REQUEST = 'FETCH_EXPENDITURES_REQUEST';
export const FETCH_EXPENDITURES_SUCCESS = 'FETCH_EXPENDITURES_SUCCESS';
export const FETCH_EXPENDITURES_FAILURE = 'FETCH_EXPENDITURES_FAILURE';
export const FETCH_EXPENDITURES_STUDENT_PAYMENTS_SUM_SUCCESS = 'FETCH_EXPENDITURES_STUDENT_PAYMENTS_SUM_SUCCESS'

export const ADD_EXPENDITURE_REQUEST = 'ADD_EXPENDITURE_REQUEST';
export const ADD_EXPENDITURE_SUCCESS = 'ADD_EXPENDITURE_SUCCESS';
export const ADD_EXPENDITURE_FAILURE = 'ADD_EXPENDITURE_FAILURE';

export const DELETE_EXPENDITURE_REQUEST = 'DELETE_EXPENDITURE_REQUEST';
export const DELETE_EXPENDITURE_SUCCESS = 'DELETE_EXPENDITURE_SUCCESS';
export const DELETE_EXPENDITURE_FAILURE = 'DELETE_EXPENDITURE_FAILURE';

// Optional: Add constants for updating if you implement that feature
export const UPDATE_EXPENDITURE_REQUEST = 'UPDATE_EXPENDITURE_REQUEST';
export const UPDATE_EXPENDITURE_SUCCESS = 'UPDATE_EXPENDITURE_SUCCESS';
export const UPDATE_EXPENDITURE_FAILURE = 'UPDATE_EXPENDITURE_FAILURE';

// ... (existing types)

export const FETCH_EXPENDITURES_SUM_SUCCESS = 'FETCH_EXPENDITURES_SUM_SUCCESS'; // New

export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR'; // Add this new type
export const RESET_LOADING_STATE = 'RESET_LOADING_STATE';

// Student Exams Action Types
export const FETCH_STUDENT_EXAMS_REQUEST = "FETCH_STUDENT_EXAMS_REQUEST";
export const FETCH_STUDENT_EXAMS_SUCCESS = "FETCH_STUDENT_EXAMS_SUCCESS";
export const FETCH_STUDENT_EXAMS_FAILURE = "FETCH_STUDENT_EXAMS_FAILURE";

export const ADD_STUDENT_EXAM_REQUEST = "ADD_STUDENT_EXAM_REQUEST";
export const ADD_STUDENT_EXAM_SUCCESS = "ADD_STUDENT_EXAM_SUCCESS";
export const ADD_STUDENT_EXAM_FAILURE = "ADD_STUDENT_EXAM_FAILURE";

export const UPDATE_STUDENT_EXAM_REQUEST = "UPDATE_STUDENT_EXAM_REQUEST";
export const UPDATE_STUDENT_EXAM_SUCCESS = "UPDATE_STUDENT_EXAM_SUCCESS";
export const UPDATE_STUDENT_EXAM_FAILURE = "UPDATE_STUDENT_EXAM_FAILURE";

export const DELETE_STUDENT_EXAM_REQUEST = "DELETE_STUDENT_EXAM_REQUEST";
export const DELETE_STUDENT_EXAM_SUCCESS = "DELETE_STUDENT_EXAM_SUCCESS";
export const DELETE_STUDENT_EXAM_FAILURE = "DELETE_STUDENT_EXAM_FAILURE";
// types.js

export const SAVE_OR_FETCH_AUTOTIMETABLES_REQUEST = 'SAVE_OR_FETCH_AUTOTIMETABLES_REQUEST';
export const SAVE_OR_FETCH_AUTOTIMETABLES_SUCCESS = 'SAVE_OR_FETCH_AUTOTIMETABLES_SUCCESS';
export const SAVE_OR_FETCH_AUTOTIMETABLES_FAILURE = 'SAVE_OR_FETCH_AUTOTIMETABLES_FAILURE';

// Action Types for a clear state management
export const FETCH_CLASS_UPDATES_START = 'FETCH_CLASS_UPDATES_START';
export const FETCH_CLASS_UPDATES_SUCCESS = 'FETCH_CLASS_UPDATES_SUCCESS';
export const FETCH_CLASS_UPDATES_FAILURE = 'FETCH_CLASS_UPDATES_FAILURE';

export const FETCH_MONTHLY_PAYMENTS_SUCCESS = 'FETCH_MONTHLY_PAYMENTS_SUCCESS';

export const  FETCH_ALL_MONTHLY_PAYMENTS_REQUEST = "FETCH_ALL_MONTHLY_PAYMENTS_REQUEST"
export const  FETCH_ALL_MONTHLY_PAYMENTS_SUCCESS = "FETCH_ALL_MONTHLY_PAYMENTS_SUCCESS"
export const  FETCH_ALL_MONTHLY_PAYMENTS_FAILURE = "FETCH_ALL_MONTHLY_PAYMENTS_FAILURE"


// SYLLABUS ACTIONS
export const UPDATE_SYLLABUS_REQUEST = "UPDATE_SYLLABUS_REQUEST";
export const UPDATE_SYLLABUS_SUCCESS = "UPDATE_SYLLABUS_SUCCESS";
export const UPDATE_SYLLABUS_FAILURE = "UPDATE_SYLLABUS_FAILURE";

export const UPDATE_EMPLOYEE_REQUEST = "UPDATE_EMPLOYEE_REQUEST";
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_FAILURE = "UPDATE_EMPLOYEE_FAILURE";

export const REVISION_PROGRAM_REGISTER_REQUEST = "REVISION_PROGRAM_REGISTER_REQUEST";
export const REVISION_PROGRAM_REGISTER_SUCCESS = "REVISION_PROGRAM_REGISTER_SUCCESS";
export const REVISION_PROGRAM_REGISTER_FAILURE = "REVISION_PROGRAM_REGISTER_FAILURE";

export const FETCH_REVISION_STUDENTS_REQUEST = "FETCH_REVISION_STUDENTS_REQUEST";
export const FETCH_REVISION_STUDENTS_SUCCESS = "FETCH_REVISION_STUDENTS_SUCCESS";
export const FETCH_REVISION_STUDENTS_FAILURE = "FETCH_REVISION_STUDENTS_FAILURE";

export const DELETE_REVISION_STUDENT_REQUEST = "DELETE_REVISION_STUDENT_REQUEST";
export const DELETE_REVISION_STUDENT_SUCCESS = "DELETE_REVISION_STUDENT_SUCCESS";
export const DELETE_REVISION_STUDENT_FAILURE = "DELETE_REVISION_STUDENT_FAILURE"; 


// types.js
export const UPDATE_PAYMENT_STATUS_REQUEST = "UPDATE_PAYMENT_STATUS_REQUEST";
export const UPDATE_PAYMENT_STATUS_SUCCESS = "UPDATE_PAYMENT_STATUS_SUCCESS";
export const UPDATE_PAYMENT_STATUS_FAILURE = "UPDATE_PAYMENT_STATUS_FAILURE";


export const UPDATE_STUDENT_STATUS_REQUEST = 'UPDATE_STUDENT_STATUS_REQUEST';
export const UPDATE_STUDENT_STATUS_SUCCESS = 'UPDATE_STUDENT_STATUS_SUCCESS';
export const UPDATE_STUDENT_STATUS_FAILURE = 'UPDATE_STUDENT_STATUS_FAILURE';

export const FETCH_LECTURE_MATERIALS_REQUEST = "FETCH_LECTURE_MATERIALS_REQUEST";
export const FETCH_LECTURE_MATERIALS_SUCCESS = "FETCH_LECTURE_MATERIALS_SUCCESS";
export const FETCH_LECTURE_MATERIALS_FAILURE = "FETCH_LECTURE_MATERIALS_FAILURE";

export const UPLOAD_LECTURE_MATERIAL_REQUEST = "UPLOAD_LECTURE_MATERIAL_REQUEST";
export const UPLOAD_LECTURE_MATERIAL_SUCCESS = "UPLOAD_LECTURE_MATERIAL_SUCCESS";
export const UPLOAD_LECTURE_MATERIAL_FAILURE = "UPLOAD_LECTURE_MATERIAL_FAILURE";

export const DELETE_LECTURE_MATERIAL_SUCCESS = 'DELETE_LECTURE_MATERIAL_SUCCESS';
export const DELETE_LECTURE_MATERIAL_FAILURE = 'DELETE_LECTURE_MATERIAL_FAILURE';
export const DELETE_LECTURE_MATERIAL_REQUEST = 'DELETE_LECTURE_MATERIAL_REQUEST';

// New types for Revision Classes/Attendance
export const FETCH_REVISION_CLASSES_REQUEST = "FETCH_REVISION_CLASSES_REQUEST";
export const FETCH_REVISION_CLASSES_SUCCESS = "FETCH_REVISION_CLASSES_SUCCESS";
export const FETCH_REVISION_CLASSES_FAILURE = "FETCH_REVISION_CLASSES_FAILURE";

export const UPDATE_CLASS_ATTENDANCE_REQUEST = "UPDATE_CLASS_ATTENDANCE_REQUEST";
export const UPDATE_CLASS_ATTENDANCE_SUCCESS = "UPDATE_CLASS_ATTENDANCE_SUCCESS";
export const UPDATE_CLASS_ATTENDANCE_FAILURE = "UPDATE_CLASS_ATTENDANCE_FAILURE";

// Additional action types for revision classes exam data
export const ADD_REVISION_CLASS_EXAM_SUCCESS = 'ADD_REVISION_CLASS_EXAM_SUCCESS';
export const UPDATE_REVISION_CLASS_EXAM_SUCCESS = 'UPDATE_REVISION_CLASS_EXAM_SUCCESS';
export const SET_REVISION_CLASS_EXAM_DATA = 'SET_REVISION_CLASS_EXAM_DATA';

export const FETCH_REVISION_EXAMS_REQUEST = 'FETCH_REVISION_EXAMS_REQUEST';
export const FETCH_REVISION_EXAMS_SUCCESS = 'FETCH_REVISION_EXAMS_SUCCESS';
export const FETCH_REVISION_EXAMS_FAILURE = 'FETCH_REVISION_EXAMS_FAILURE';
export const ADD_REVISION_EXAM_SUCCESS = 'ADD_REVISION_EXAM_SUCCESS';
export const UPDATE_REVISION_EXAM_SUCCESS = 'UPDATE_REVISION_EXAM_SUCCESS';

// revisionFeeActions.js
export const UPDATE_REVISION_FEE_REQUEST = 'UPDATE_REVISION_FEE_REQUEST';
export const UPDATE_REVISION_FEE_SUCCESS = 'UPDATE_REVISION_FEE_SUCCESS'; 
export const UPDATE_REVISION_FEE_FAILURE = 'UPDATE_REVISION_FEE_FAILURE';
export const RESET_EMPLOYEE_LOADING_STATE = 'RESET_EMPLOYEE_LOADING_STATE';
// ... other types
// src/redux/types.js
export const FETCH_CLASS_SCHEDULE_REQUEST = 'FETCH_CLASS_SCHEDULE_REQUEST';
export const FETCH_CLASS_SCHEDULE_SUCCESS = 'FETCH_CLASS_SCHEDULE_SUCCESS';
export const FETCH_CLASS_SCHEDULE_FAILURE = 'FETCH_CLASS_SCHEDULE_FAILURE';
export const UPDATE_CLASS_SCHEDULE_REQUEST = 'UPDATE_CLASS_SCHEDULE_REQUEST';
export const UPDATE_CLASS_SCHEDULE_SUCCESS = 'UPDATE_CLASS_SCHEDULE_SUCCESS';
export const UPDATE_CLASS_SCHEDULE_FAILURE = 'UPDATE_CLASS_SCHEDULE_FAILURE';

export const SET_CURRENT_STUDENT = 'SET_CURRENT_STUDENT';
export const CLEAR_CURRENT_STUDENT = 'CLEAR_CURRENT_STUDENT';

// Action Types for Student Classes
export const FETCH_STUDENT_CLASSES_REQUEST = 'FETCH_STUDENT_CLASSES_REQUEST';
export const FETCH_STUDENT_CLASSES_SUCCESS = 'FETCH_STUDENT_CLASSES_SUCCESS';
export const FETCH_STUDENT_CLASSES_FAILURE = 'FETCH_STUDENT_CLASSES_FAILURE';

// Add to your types file
export const SEARCH_STUDENT_CLASSES_REQUEST = 'SEARCH_STUDENT_CLASSES_REQUEST';
export const SEARCH_STUDENT_CLASSES_SUCCESS = 'SEARCH_STUDENT_CLASSES_SUCCESS';
export const SEARCH_STUDENT_CLASSES_FAILURE = 'SEARCH_STUDENT_CLASSES_FAILURE';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';

// Add to your types file
export const FETCH_YEAR_STATISTICS_REQUEST = 'FETCH_YEAR_STATISTICS_REQUEST';
export const FETCH_YEAR_STATISTICS_SUCCESS = 'FETCH_YEAR_STATISTICS_SUCCESS';
export const FETCH_YEAR_STATISTICS_FAILURE = 'FETCH_YEAR_STATISTICS_FAILURE';

// Action Types
export const FETCH_ATTENDANCE_SUMMARY_REQUEST = 'FETCH_ATTENDANCE_SUMMARY_REQUEST';
export const FETCH_ATTENDANCE_SUMMARY_SUCCESS = 'FETCH_ATTENDANCE_SUMMARY_SUCCESS';
export const FETCH_ATTENDANCE_SUMMARY_FAILURE = 'FETCH_ATTENDANCE_SUMMARY_FAILURE';

// types.js
export const BOOK_DEMO_REQUEST = 'BOOK_DEMO_REQUEST';
export const BOOK_DEMO_SUCCESS = 'BOOK_DEMO_SUCCESS';
export const BOOK_DEMO_FAILURE = 'BOOK_DEMO_FAILURE';

export const FETCH_DEMO_BOOKINGS_REQUEST = 'FETCH_DEMO_BOOKINGS_REQUEST';
export const FETCH_DEMO_BOOKINGS_SUCCESS = 'FETCH_DEMO_BOOKINGS_SUCCESS';
export const FETCH_DEMO_BOOKINGS_FAILURE = 'FETCH_DEMO_BOOKINGS_FAILURE';

export const UPDATE_DEMO_STATUS_REQUEST = 'UPDATE_DEMO_STATUS_REQUEST';
export const UPDATE_DEMO_STATUS_SUCCESS = 'UPDATE_DEMO_STATUS_SUCCESS';
export const UPDATE_DEMO_STATUS_FAILURE = 'UPDATE_DEMO_STATUS_FAILURE';

export const FETCH_STUDENT_PPTS_REQUEST = 'FETCH_STUDENT_PPTS_REQUEST';
export const FETCH_STUDENT_PPTS_SUCCESS = 'FETCH_STUDENT_PPTS_SUCCESS';
export const FETCH_STUDENT_PPTS_FAILURE = 'FETCH_STUDENT_PPTS_FAILURE';

// Student Worksheets Types
export const FETCH_STUDENT_WORKSHEETS_REQUEST = 'FETCH_STUDENT_WORKSHEETS_REQUEST';
export const FETCH_STUDENT_WORKSHEETS_SUCCESS = 'FETCH_STUDENT_WORKSHEETS_SUCCESS';
export const FETCH_STUDENT_WORKSHEETS_FAILURE = 'FETCH_STUDENT_WORKSHEETS_FAILURE';

export const FETCH_MONTHLY_PAYMENT_DETAILS_REQUEST = 'FETCH_MONTHLY_PAYMENT_DETAILS_REQUEST';
export const FETCH_MONTHLY_PAYMENT_DETAILS_SUCCESS = 'FETCH_MONTHLY_PAYMENT_DETAILS_SUCCESS';
export const FETCH_MONTHLY_PAYMENT_DETAILS_FAILURE = 'FETCH_MONTHLY_PAYMENT_DETAILS_FAILURE';

// Add this to your existing types
export const CLEAR_MONTHLY_PAYMENT_DETAILS = 'CLEAR_MONTHLY_PAYMENT_DETAILS';

export const FETCH_ACADEMY_FINANCE_REQUEST = 'FETCH_ACADEMY_FINANCE_REQUEST';
export const FETCH_ACADEMY_FINANCE_SUCCESS = 'FETCH_ACADEMY_FINANCE_SUCCESS';
export const FETCH_ACADEMY_FINANCE_FAILURE = 'FETCH_ACADEMY_FINANCE_FAILURE';

export const ADD_ACADEMY_EARNING_REQUEST = 'ADD_ACADEMY_EARNING_REQUEST';
export const ADD_ACADEMY_EARNING_SUCCESS = 'ADD_ACADEMY_EARNING_SUCCESS';
export const ADD_ACADEMY_EARNING_FAILURE = 'ADD_ACADEMY_EARNING_FAILURE';
export const UPLOAD_STUDY_MATERIAL_REQUEST = 'UPLOAD_STUDY_MATERIAL_REQUEST';
export const UPLOAD_STUDY_MATERIAL_SUCCESS = 'UPLOAD_STUDY_MATERIAL_SUCCESS';
export const UPLOAD_STUDY_MATERIAL_FAILURE = 'UPLOAD_STUDY_MATERIAL_FAILURE';

export const UPLOAD_QUESTION_PAPER_REQUEST = 'UPLOAD_QUESTION_PAPER_REQUEST';
export const UPLOAD_QUESTION_PAPER_SUCCESS = 'UPLOAD_QUESTION_PAPER_SUCCESS';
export const UPLOAD_QUESTION_PAPER_FAILURE = 'UPLOAD_QUESTION_PAPER_FAILURE';

export const FETCH_STUDY_MATERIALS_REQUEST = 'FETCH_STUDY_MATERIALS_REQUEST';
export const FETCH_STUDY_MATERIALS_SUCCESS = 'FETCH_STUDY_MATERIALS_SUCCESS';
export const FETCH_STUDY_MATERIALS_FAILURE = 'FETCH_STUDY_MATERIALS_FAILURE';

export const FETCH_QUESTION_PAPERS_REQUEST = 'FETCH_QUESTION_PAPERS_REQUEST';
export const FETCH_QUESTION_PAPERS_SUCCESS = 'FETCH_QUESTION_PAPERS_SUCCESS';
export const FETCH_QUESTION_PAPERS_FAILURE = 'FETCH_QUESTION_PAPERS_FAILURE';

export const SET_STUDENTS_NEED_REFRESH = 'SET_STUDENTS_NEED_REFRESH'

export const FETCH_TUTOR_IDEAS_REQUEST = 'FETCH_TUTOR_IDEAS_REQUEST';
export const FETCH_TUTOR_IDEAS_SUCCESS = 'FETCH_TUTOR_IDEAS_SUCCESS';
export const FETCH_TUTOR_IDEAS_FAILURE = 'FETCH_TUTOR_IDEAS_FAILURE';

export const ADD_TUTOR_IDEA_REQUEST = 'ADD_TUTOR_IDEA_REQUEST';
export const ADD_TUTOR_IDEA_SUCCESS = 'ADD_TUTOR_IDEA_SUCCESS';
export const ADD_TUTOR_IDEA_FAILURE = 'ADD_TUTOR_IDEA_FAILURE';

export const UPDATE_TUTOR_IDEA_REQUEST = 'UPDATE_TUTOR_IDEA_REQUEST';
export const UPDATE_TUTOR_IDEA_SUCCESS = 'UPDATE_TUTOR_IDEA_SUCCESS';
export const UPDATE_TUTOR_IDEA_FAILURE = 'UPDATE_TUTOR_IDEA_FAILURE';

// Action Types
export const FETCH_EXAM_CONSOLIDATION_REQUEST = "FETCH_EXAM_CONSOLIDATION_REQUEST";
export const FETCH_EXAM_CONSOLIDATION_SUCCESS = "FETCH_EXAM_CONSOLIDATION_SUCCESS"; 
export const FETCH_EXAM_CONSOLIDATION_FAILURE = "FETCH_EXAM_CONSOLIDATION_FAILURE";

// Delete Academy Earning Action Types
export const DELETE_ACADEMY_EARNING_REQUEST = "DELETE_ACADEMY_EARNING_REQUEST";
export const DELETE_ACADEMY_EARNING_SUCCESS = "DELETE_ACADEMY_EARNING_SUCCESS";
export const DELETE_ACADEMY_EARNING_FAILURE = "DELETE_ACADEMY_EARNING_FAILURE";


// Add these action types
export const UPDATE_ACADEMY_EARNING_REQUEST = "UPDATE_ACADEMY_EARNING_REQUEST";
export const UPDATE_ACADEMY_EARNING_SUCCESS = "UPDATE_ACADEMY_EARNING_SUCCESS";
export const UPDATE_ACADEMY_EARNING_FAILURE = "UPDATE_ACADEMY_EARNING_FAILURE";

// src/redux/types.js - Add these types
export const FETCH_MONTHLY_STUDENT_DETAILS_REQUEST = 'FETCH_MONTHLY_STUDENT_DETAILS_REQUEST';
export const FETCH_MONTHLY_STUDENT_DETAILS_SUCCESS = 'FETCH_MONTHLY_STUDENT_DETAILS_SUCCESS';
export const FETCH_MONTHLY_STUDENT_DETAILS_FAILURE = 'FETCH_MONTHLY_STUDENT_DETAILS_FAILURE';
export const CLEAR_MONTHLY_STUDENT_DETAILS = 'CLEAR_MONTHLY_STUDENT_DETAILS';


export const UPLOAD_STUDENT_DATA_REQUEST = 'UPLOAD_STUDENT_DATA_REQUEST';
export const UPLOAD_STUDENT_DATA_SUCCESS = 'UPLOAD_STUDENT_DATA_SUCCESS';
export const UPLOAD_STUDENT_DATA_FAILURE = 'UPLOAD_STUDENT_DATA_FAILURE';

// Fetch Upload History
export const FETCH_UPLOAD_HISTORY_REQUEST = 'FETCH_UPLOAD_HISTORY_REQUEST';
export const FETCH_UPLOAD_HISTORY_SUCCESS = 'FETCH_UPLOAD_HISTORY_SUCCESS';
export const FETCH_UPLOAD_HISTORY_FAILURE = 'FETCH_UPLOAD_HISTORY_FAILURE';

// Delete Upload
export const DELETE_UPLOAD_REQUEST = 'DELETE_UPLOAD_REQUEST';
export const DELETE_UPLOAD_SUCCESS = 'DELETE_UPLOAD_SUCCESS';
export const DELETE_UPLOAD_FAILURE = 'DELETE_UPLOAD_FAILURE';

// Create Lead
export const CREATE_LEAD_REQUEST = 'CREATE_LEAD_REQUEST';
export const CREATE_LEAD_SUCCESS = 'CREATE_LEAD_SUCCESS';
export const CREATE_LEAD_FAILURE = 'CREATE_LEAD_FAILURE';

// Fetch Leads
export const FETCH_LEADS_REQUEST = 'FETCH_LEADS_REQUEST';
export const FETCH_LEADS_SUCCESS = 'FETCH_LEADS_SUCCESS';
export const FETCH_LEADS_FAILURE = 'FETCH_LEADS_FAILURE';

// Update Lead Status
export const UPDATE_LEAD_STATUS_REQUEST = 'UPDATE_LEAD_STATUS_REQUEST';
export const UPDATE_LEAD_STATUS_SUCCESS = 'UPDATE_LEAD_STATUS_SUCCESS';
export const UPDATE_LEAD_STATUS_FAILURE = 'UPDATE_LEAD_STATUS_FAILURE';

export const ADD_STUDENT_SYLLABUS_REQUEST = "ADD_STUDENT_SYLLABUS_REQUEST";
export const ADD_STUDENT_SYLLABUS_SUCCESS = "ADD_STUDENT_SYLLABUS_SUCCESS";
export const ADD_STUDENT_SYLLABUS_FAILURE = "ADD_STUDENT_SYLLABUS_FAILURE";

export const FETCH_STUDENT_SYLLABUS_REQUEST = "FETCH_STUDENT_SYLLABUS_REQUEST";
export const FETCH_STUDENT_SYLLABUS_SUCCESS = "FETCH_STUDENT_SYLLABUS_SUCCESS";
export const FETCH_STUDENT_SYLLABUS_FAILURE = "FETCH_STUDENT_SYLLABUS_FAILURE";

export const FETCH_NOTIFICATIONS_REQUEST = "FETCH_NOTIFICATIONS_REQUEST";
export const FETCH_NOTIFICATIONS_SUCCESS = "FETCH_NOTIFICATIONS_SUCCESS";
export const FETCH_NOTIFICATIONS_FAILURE = "FETCH_NOTIFICATIONS_FAILURE";

export const MARK_NOTIFICATION_READ_REQUEST = "MARK_NOTIFICATION_READ_REQUEST";
export const MARK_NOTIFICATION_READ_SUCCESS = "MARK_NOTIFICATION_READ_SUCCESS";
export const MARK_NOTIFICATION_READ_FAILURE = "MARK_NOTIFICATION_READ_FAILURE";

export const FETCH_EMPLOYEE_REQUEST = 'FETCH_EMPLOYEE_REQUEST';
export const FETCH_EMPLOYEE_SUCCESS = 'FETCH_EMPLOYEE_SUCCESS';
export const FETCH_EMPLOYEE_FAILURE = 'FETCH_EMPLOYEE_FAILURE';

export const FETCH_EMPLOYEE_PAYMENTS_REQUEST = 'FETCH_EMPLOYEE_PAYMENTS_REQUEST';
export const FETCH_EMPLOYEE_PAYMENTS_SUCCESS = 'FETCH_EMPLOYEE_PAYMENTS_SUCCESS';
export const FETCH_EMPLOYEE_PAYMENTS_FAILURE = 'FETCH_EMPLOYEE_PAYMENTS_FAILURE';

export const SET_CURRENT_EMPLOYEE = 'SET_CURRENT_EMPLOYEE';
